# Site settings
title: FABrikations LABor
header-img: img/home-bg.jpg
email: info@fabrikationslabor.de
description: "Das offizielle Blog der deutschen FabLabs (FabLab4Germany) - was ist ein FabLab?"
baseurl: ""
url: "http://www.fabrikationslabor.de"
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
